### ISSUE TITLE
The clicked tag is not highlighted with single click

### ISSUE THREAD

**Issue by Anduin2017** [joeattardi/emoji-button#50] opened 2020-04-26 15:32 UTC
The clicked tag is not highlighted with a single click. But the content has scrolled to the correct position.

The tag is always correctly highlighted with a double click:

Repro video:

https://probe.cdn.aiursoft.com/anduins-site/out.mp4

**Comment by joeattardi** [comment] 2020-04-26 15:43
Are you getting any errors in the console?

**Comment by Anduin2017** [comment] 2020-04-26 16:51
No error. Seems it was because that the view was not scrolled to the correct position.

**Comment by joeattardi** [comment] 2020-04-27 03:48
I can't seem to reproduce this in any browser. I tried Chrome, Firefox, Safari, and Edge. Are you running on Windows? Maybe it's some quirk specific to Windows.

**Comment by Anduin2017** [comment] 2020-04-27 05:08
Hi, @joeattardi , I also tried Google chrome on Windows 10 and Microsoft Edge (Chromium) and it happens on both the browsers.

But, after the tab click, a tinny scroll(Even 1 pixel) will highlight the correct tab.

**Comment by Anduin2017** [comment] 2020-04-27 06:57
I have an update! This bug only happens when the scale of the OS or browser is not 100%.

Repro video:

https://probe.cdn.aiursoft.com/anduins-site/out2.mp4

**Comment by joeattardi** [comment] 2020-04-27 10:23
Aha! I can reproduce it now. Will take a look, thanks!

**Comment by joeattardi** [comment] 2020-04-28 00:52
I tested this pretty thoroughly, looks like this should be fixed now with v3.0.2. Please give it a try and let me know if you still have the issue! Feel free to re-open if you still run into the issue.

**Closed by joeattardi** 2020-04-28 00:52 UTC
Labels: bug
