### ISSUE TITLE
picker to be too large

### ISSUE THREAD

**Issue by guangzan** [joeattardi/emoji-button#41] opened 2020-04-01 13:02 UTC
My project itself uses rem, which causes the picker to be too large. How to solve it？

**Comment by joeattardi** [comment] 2020-04-01 16:44
Can you elaborate on this issue, maybe provide a screenshot? I'm not sure what the issue is that you're describing. Thanks!

**Comment by joeattardi** [comment] 2020-04-04 22:30
Hi, just wanted to ping you again. Can you give me some more information on the problem you’re having?

**Comment by guangzan** [comment] 2020-04-05 08:16
Thank you for your reply. The reason is that Emoji's CSS default unit is rem, and my HTML root element font size is 54px, so Emoji looks very big. I solved this problem by rerun build your project, and I converted the CSS unit to PX. The problem is not your plug-in. I'm sorry that I didn't reply to you in time and didn't describe the problem clearly.

**Comment by joeattardi** [comment] 2020-04-05 14:39
Ah, I understand the issue now. You are probably not the only one to run into this - since the picker sizes are all specified in rem units. 

What I can do is change these all to be em units, and add a configuration option to set the base font size with a sensible default. 

I am currently in the process of working on a major new update and I can definitely add this fix to it. 

Thanks for reporting!

**Comment by joeattardi** [comment] 2020-04-05 17:51
Ok, this will be fixed in 3.0. The base font size of the picker is set to 16px and everything is specified using `em` rather than `rem`.

**Closed by joeattardi** 2020-04-05 17:51 UTC
Labels: bug
