### ISSUE TITLE
Keep Emoji Picker Open

### ISSUE THREAD

**Issue by mattWalters0** [joeattardi/emoji-button#145] opened 2021-04-16 14:46 UTC
Is it possible to keep the emoji picker open even if you click outside it?  

I'm trying to use the picker on a mobile screen and I would like it to be displayed all the time. Is there any way to achieve this with Emoji Button? 

Thanks!

**Comment by cyberfly** [comment] 2021-04-22 05:00
@mattWalters0 you can https://emoji-button.js.org/docs/customize

**Comment by mattWalters0** [comment] 2021-04-22 17:11
Thanks @cyberfly.  I saw this option but the Picker still closes if you click or tap outside it..  I really want it to be displayed all the time but not sure if that's possible...

**Comment by joeattardi** [comment] 2021-06-04 06:06
Duplicate of #136, I will try to add support for this in v5.

**Closed by joeattardi** 2021-06-04 06:06 UTC
Labels: duplicate
